[package]
name = "qqkey"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
chrono = "0.4.39"
cookie_store = "0.21.1"
flexi_logger = "0.29.8"
log = "0.4.25"
rand = "0.9.0"
regex = "1.11.1"
reqwest = { version = "0.12.7", features = ["cookies", "json", "socks"] }
reqwest_cookie_store = { version = "0.8.0", features = ["serde"] }
serde = { version = "1.0.217", features = ["derive", "rc"] }
serde_json = "1.0.138"
tokio = { version = "1.43.0", features = ["full"] }
urlencoding = "2.1.3"
thiserror = "2.0"
serde-error = "0.1"
url = { version = "2.5.2", features = ["serde"] }
