add_rules("mode.debug", "mode.release")

set_project("m0n1t0r-sdk-cpp")
set_version("0.0.1", {build = "%Y%m%d%H%M"})
set_license("LGPL-3.0")

includes("xmake")

target("m0n1t0r-sdk-cpp")
    set_kind("static")
    set_languages("c++17")
    set_warnings("all", "error")

    add_includedirs("src/include")
    add_includedirs("include", { public = true })
    add_headerfiles("include/**.h", { prefixdir = "m0n1t0r-sdk-cpp" })
    add_files("src/*.cpp")
    add_files("src/server/*.cpp")
    add_files("src/client/*.cpp")

    add_packages("vcpkg::boost-random~Static")
    add_packages("vcpkg::boost-filesystem~Static")
    add_packages("vcpkg::boost-atomic~Static")
    add_packages("websocketpp~Static")
    add_packages("spdlog~Static")
    add_packages("cpr~Static")
    add_packages("nlohmann_json~Static")
    add_packages("upa-url~Static")
    add_packages("cpp-channel~Static")
    add_packages("fmt~Static")

for _, file in ipairs(os.files("src/test/**.cpp")) do
     local name = path.basename(file)
     target("test" .. name)
        set_kind("binary")
        set_languages("c++17")
        set_default(false)
        add_files("src/test/" .. name .. ".cpp")
        add_tests("default")
        add_deps("m0n1t0r-sdk-cpp")

        add_packages("vcpkg::boost-random~Static")
        add_packages("vcpkg::boost-filesystem~Static")
        add_packages("vcpkg::boost-atomic~Static")
        add_packages("websocketpp~Static")
        add_packages("spdlog~Static")
        add_packages("cpr~Static")
        add_packages("nlohmann_json~Static")
        add_packages("upa-url~Static")
        add_packages("cpp-channel~Static")
        add_packages("fmt~Static")
end
