name: Build Debug UI on Windows

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - uses: xmake-io/github-action-setup-xmake@v1

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Setup vcpkg
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgGitCommitId: 'cd124b84feb0c02a24a2d90981e8358fdee0e077'

    - name: Integrate vcpkg
      run: vcpkg integrate install
        
    - name: Install boost
      run: vcpkg install boost:x64-windows-static

    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: 6.8.0
        dir: ${{ github.workspace }}/qt/
        modules: 'qtwebsockets'

    - name: Build debug sdk
      run: cd ./m0n1t0r-sdk && xmake f -m debug --runtimes=MTd -y -v && xmake build -y -v && xmake package && cd ..

    - name: Build debug ui
      run: cd ./m0n1t0r-ui && xmake f -m debug --runtimes=MTd --qt=${{ github.workspace }}/qt/ --toolchain=msvc -v -y && xmake build -y -v && cd ..
